name: hordricweather
description: "HordricWeather - Application météorologique élégante et intuitive"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dotenv: ^4.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  intl: ^0.20.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  timezone: ^0.9.4
  home_widget: ^0.8.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#90B2F9"
  adaptive_icon_foreground: "assets/img.png"

flutter:
  uses-material-design: true

  assets:
    - assets/