class City {
  bool isSelected;
  final String city;
  final String country;
  final bool isDefault;
  final String? region;
  final double? latitude;
  final double? longitude;
  final String? flag; // Nouveau champ pour les drapeaux

  City(
      {required this.isSelected,
      required this.city,
      required this.country,
      required this.isDefault,
      this.region,
      this.latitude,
      this.longitude,
      this.flag});

  // Liste complète des villes avec focus sur le Togo et le monde entier
  static List<City> citiesList = [
    // TOGO - Toutes les villes principales et communes
    City(
        isSelected: false,
        city: 'Lomé',
        country: 'Togo',
        isDefault: false, // Changé pour qu'il apparaisse dans la liste
        region: 'Maritime',
        latitude: 6.1375,
        longitude: 1.2123,
        flag: '🇹🇬'),
    City(
        isSelected: false,
        city: 'Sokodé',
        country: 'Togo',
        isDefault: false,
        region: 'Centrale',
        latitude: 8.9833,
        longitude: 1.1333,
        flag: '🇹🇬'),
    City(
        isSelected: false,
        city: 'Kara',
        country: 'Togo',
        isDefault: false,
        region: 'Kara',
        latitude: 9.5511,
        longitude: 1.1867,
        flag: '🇹🇬'),
    City(
        isSelected: false,
        city: 'Atakpamé',
        country: 'Togo',
        isDefault: false,
        region: 'Plateaux',
        latitude: 7.5333,
        longitude: 1.1333,
        flag: '🇹🇬'),
    City(
        isSelected: false,
        city: 'Dapaong',
        country: 'Togo',
        isDefault: false,
        region: 'Savanes',
        latitude: 10.8667,
        longitude: 0.2167,
        flag: '🇹🇬'),
    City(
        isSelected: false,
        city: 'Tsévié',
        country: 'Togo',
        isDefault: false,
        region: 'Maritime',
        latitude: 6.4267,
        longitude: 1.2133,
        flag: '🇹🇬'),
    City(
        isSelected: false,
        city: 'Aného',
        country: 'Togo',
        isDefault: false,
        region: 'Maritime',
        latitude: 6.2333,
        longitude: 1.6000,
        flag: '🇹🇬'),
    City(
        isSelected: false,
        city: 'Kpalimé',
        country: 'Togo',
        isDefault: false,
        region: 'Plateaux',
        latitude: 6.9000,
        longitude: 0.6333,
        flag: '🇹🇬'),
    City(
        isSelected: false,
        city: 'Bassar',
        country: 'Togo',
        isDefault: false,
        region: 'Kara',
        latitude: 9.2500,
        longitude: 0.7833,
        flag: '🇹🇬'),

    // VILLES MONDIALES MASSIVES AVEC DRAPEAUX

    // FRANCE
    City(
        isSelected: false,
        city: 'Paris',
        country: 'France',
        isDefault: false,
        latitude: 48.8566,
        longitude: 2.3522,
        flag: '🇫🇷'),
    City(
        isSelected: false,
        city: 'Marseille',
        country: 'France',
        isDefault: false,
        latitude: 43.2965,
        longitude: 5.3698,
        flag: '🇫🇷'),
    City(
        isSelected: false,
        city: 'Lyon',
        country: 'France',
        isDefault: false,
        latitude: 45.7640,
        longitude: 4.8357,
        flag: '🇫🇷'),
    City(
        isSelected: false,
        city: 'Toulouse',
        country: 'France',
        isDefault: false,
        latitude: 43.6047,
        longitude: 1.4442,
        flag: '🇫🇷'),
    City(
        isSelected: false,
        city: 'Nice',
        country: 'France',
        isDefault: false,
        latitude: 43.7102,
        longitude: 7.2620,
        flag: '🇫🇷'),
    City(
        isSelected: false,
        city: 'Nantes',
        country: 'France',
        isDefault: false,
        latitude: 47.2184,
        longitude: -1.5536,
        flag: '🇫🇷'),
    City(
        isSelected: false,
        city: 'Strasbourg',
        country: 'France',
        isDefault: false,
        latitude: 48.5734,
        longitude: 7.7521,
        flag: '🇫🇷'),
    City(
        isSelected: false,
        city: 'Bordeaux',
        country: 'France',
        isDefault: false,
        latitude: 44.8378,
        longitude: -0.5792,
        flag: '🇫🇷'),

    // ROYAUME-UNI
    City(
        isSelected: false,
        city: 'Londres',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 51.5074,
        longitude: -0.1278,
        flag: '🇬🇧'),
    City(
        isSelected: false,
        city: 'Manchester',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 53.4808,
        longitude: -2.2426,
        flag: '🇬🇧'),
    City(
        isSelected: false,
        city: 'Birmingham',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 52.4862,
        longitude: -1.8904,
        flag: '🇬🇧'),
    City(
        isSelected: false,
        city: 'Liverpool',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 53.4084,
        longitude: -2.9916,
        flag: '🇬🇧'),
    City(
        isSelected: false,
        city: 'Leeds',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 53.8008,
        longitude: -1.5491,
        flag: '🇬🇧'),
    City(
        isSelected: false,
        city: 'Glasgow',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 55.8642,
        longitude: -4.2518,
        flag: '🇬🇧'),
    City(
        isSelected: false,
        city: 'Edinburgh',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 55.9533,
        longitude: -3.1883,
        flag: '🇬🇧'),

    // ALLEMAGNE
    City(
        isSelected: false,
        city: 'Berlin',
        country: 'Allemagne',
        isDefault: false,
        latitude: 52.5200,
        longitude: 13.4050,
        flag: '🇩🇪'),
    City(
        isSelected: false,
        city: 'Munich',
        country: 'Allemagne',
        isDefault: false,
        latitude: 48.1351,
        longitude: 11.5820,
        flag: '🇩🇪'),
    City(
        isSelected: false,
        city: 'Hambourg',
        country: 'Allemagne',
        isDefault: false,
        latitude: 53.5511,
        longitude: 9.9937,
        flag: '🇩🇪'),
    City(
        isSelected: false,
        city: 'Cologne',
        country: 'Allemagne',
        isDefault: false,
        latitude: 50.9375,
        longitude: 6.9603,
        flag: '🇩🇪'),
    City(
        isSelected: false,
        city: 'Francfort',
        country: 'Allemagne',
        isDefault: false,
        latitude: 50.1109,
        longitude: 8.6821,
        flag: '🇩🇪'),
    City(
        isSelected: false,
        city: 'Stuttgart',
        country: 'Allemagne',
        isDefault: false,
        latitude: 48.7758,
        longitude: 9.1829,
        flag: '🇩🇪'),
    City(
        isSelected: false,
        city: 'Düsseldorf',
        country: 'Allemagne',
        isDefault: false,
        latitude: 51.2277,
        longitude: 6.7735,
        flag: '🇩🇪'),

    // ESPAGNE
    City(
        isSelected: false,
        city: 'Madrid',
        country: 'Espagne',
        isDefault: false,
        latitude: 40.4168,
        longitude: -3.7038,
        flag: '🇪🇸'),
    City(
        isSelected: false,
        city: 'Barcelone',
        country: 'Espagne',
        isDefault: false,
        latitude: 41.3851,
        longitude: 2.1734,
        flag: '🇪🇸'),
    City(
        isSelected: false,
        city: 'Valence',
        country: 'Espagne',
        isDefault: false,
        latitude: 39.4699,
        longitude: -0.3763,
        flag: '🇪🇸'),
    City(
        isSelected: false,
        city: 'Séville',
        country: 'Espagne',
        isDefault: false,
        latitude: 37.3891,
        longitude: -5.9845,
        flag: '🇪🇸'),
    City(
        isSelected: false,
        city: 'Bilbao',
        country: 'Espagne',
        isDefault: false,
        latitude: 43.2627,
        longitude: -2.9253,
        flag: '🇪🇸'),
    City(
        isSelected: false,
        city: 'Málaga',
        country: 'Espagne',
        isDefault: false,
        latitude: 36.7213,
        longitude: -4.4216,
        flag: '🇪🇸'),

    // ITALIE
    City(
        isSelected: false,
        city: 'Rome',
        country: 'Italie',
        isDefault: false,
        latitude: 41.9028,
        longitude: 12.4964,
        flag: '🇮🇹'),
    City(
        isSelected: false,
        city: 'Milan',
        country: 'Italie',
        isDefault: false,
        latitude: 45.4642,
        longitude: 9.1900,
        flag: '🇮🇹'),
    City(
        isSelected: false,
        city: 'Naples',
        country: 'Italie',
        isDefault: false,
        latitude: 40.8518,
        longitude: 14.2681,
        flag: '🇮🇹'),
    City(
        isSelected: false,
        city: 'Turin',
        country: 'Italie',
        isDefault: false,
        latitude: 45.0703,
        longitude: 7.6869,
        flag: '🇮🇹'),
    City(
        isSelected: false,
        city: 'Venise',
        country: 'Italie',
        isDefault: false,
        latitude: 45.4408,
        longitude: 12.3155,
        flag: '🇮🇹'),
    City(
        isSelected: false,
        city: 'Florence',
        country: 'Italie',
        isDefault: false,
        latitude: 43.7696,
        longitude: 11.2558,
        flag: '🇮🇹'),

    // PAYS-BAS
    City(
        isSelected: false,
        city: 'Amsterdam',
        country: 'Pays-Bas',
        isDefault: false,
        latitude: 52.3676,
        longitude: 4.9041,
        flag: '🇳🇱'),
    City(
        isSelected: false,
        city: 'Rotterdam',
        country: 'Pays-Bas',
        isDefault: false,
        latitude: 51.9244,
        longitude: 4.4777,
        flag: '🇳🇱'),
    City(
        isSelected: false,
        city: 'La Haye',
        country: 'Pays-Bas',
        isDefault: false,
        latitude: 52.0705,
        longitude: 4.3007,
        flag: '🇳🇱'),
    City(
        isSelected: false,
        city: 'Utrecht',
        country: 'Pays-Bas',
        isDefault: false,
        latitude: 52.0907,
        longitude: 5.1214,
        flag: '🇳🇱'),

    // ÉTATS-UNIS
    City(
        isSelected: false,
        city: 'New York',
        country: 'États-Unis',
        isDefault: false,
        latitude: 40.7128,
        longitude: -74.0060,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Los Angeles',
        country: 'États-Unis',
        isDefault: false,
        latitude: 34.0522,
        longitude: -118.2437,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Chicago',
        country: 'États-Unis',
        isDefault: false,
        latitude: 41.8781,
        longitude: -87.6298,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Houston',
        country: 'États-Unis',
        isDefault: false,
        latitude: 29.7604,
        longitude: -95.3698,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Phoenix',
        country: 'États-Unis',
        isDefault: false,
        latitude: 33.4484,
        longitude: -112.0740,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Philadelphia',
        country: 'États-Unis',
        isDefault: false,
        latitude: 39.9526,
        longitude: -75.1652,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'San Antonio',
        country: 'États-Unis',
        isDefault: false,
        latitude: 29.4241,
        longitude: -98.4936,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'San Diego',
        country: 'États-Unis',
        isDefault: false,
        latitude: 32.7157,
        longitude: -117.1611,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Dallas',
        country: 'États-Unis',
        isDefault: false,
        latitude: 32.7767,
        longitude: -96.7970,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'San Jose',
        country: 'États-Unis',
        isDefault: false,
        latitude: 37.3382,
        longitude: -121.8863,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Austin',
        country: 'États-Unis',
        isDefault: false,
        latitude: 30.2672,
        longitude: -97.7431,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Jacksonville',
        country: 'États-Unis',
        isDefault: false,
        latitude: 30.3322,
        longitude: -81.6557,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'San Francisco',
        country: 'États-Unis',
        isDefault: false,
        latitude: 37.7749,
        longitude: -122.4194,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Columbus',
        country: 'États-Unis',
        isDefault: false,
        latitude: 39.9612,
        longitude: -82.9988,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Indianapolis',
        country: 'États-Unis',
        isDefault: false,
        latitude: 39.7684,
        longitude: -86.1581,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Fort Worth',
        country: 'États-Unis',
        isDefault: false,
        latitude: 32.7555,
        longitude: -97.3308,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Charlotte',
        country: 'États-Unis',
        isDefault: false,
        latitude: 35.2271,
        longitude: -80.8431,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Seattle',
        country: 'États-Unis',
        isDefault: false,
        latitude: 47.6062,
        longitude: -122.3321,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Denver',
        country: 'États-Unis',
        isDefault: false,
        latitude: 39.7392,
        longitude: -104.9903,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Washington',
        country: 'États-Unis',
        isDefault: false,
        latitude: 38.9072,
        longitude: -77.0369,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Boston',
        country: 'États-Unis',
        isDefault: false,
        latitude: 42.3601,
        longitude: -71.0589,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'El Paso',
        country: 'États-Unis',
        isDefault: false,
        latitude: 31.7619,
        longitude: -106.4850,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Nashville',
        country: 'États-Unis',
        isDefault: false,
        latitude: 36.1627,
        longitude: -86.7816,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Detroit',
        country: 'États-Unis',
        isDefault: false,
        latitude: 42.3314,
        longitude: -83.0458,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Oklahoma City',
        country: 'États-Unis',
        isDefault: false,
        latitude: 35.4676,
        longitude: -97.5164,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Portland',
        country: 'États-Unis',
        isDefault: false,
        latitude: 45.5152,
        longitude: -122.6784,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Las Vegas',
        country: 'États-Unis',
        isDefault: false,
        latitude: 36.1699,
        longitude: -115.1398,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Memphis',
        country: 'États-Unis',
        isDefault: false,
        latitude: 35.1495,
        longitude: -90.0490,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Louisville',
        country: 'États-Unis',
        isDefault: false,
        latitude: 38.2527,
        longitude: -85.7585,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Baltimore',
        country: 'États-Unis',
        isDefault: false,
        latitude: 39.2904,
        longitude: -76.6122,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Milwaukee',
        country: 'États-Unis',
        isDefault: false,
        latitude: 43.0389,
        longitude: -87.9065,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Albuquerque',
        country: 'États-Unis',
        isDefault: false,
        latitude: 35.0844,
        longitude: -106.6504,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Tucson',
        country: 'États-Unis',
        isDefault: false,
        latitude: 32.2226,
        longitude: -110.9747,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Fresno',
        country: 'États-Unis',
        isDefault: false,
        latitude: 36.7378,
        longitude: -119.7871,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Sacramento',
        country: 'États-Unis',
        isDefault: false,
        latitude: 38.5816,
        longitude: -121.4944,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Mesa',
        country: 'États-Unis',
        isDefault: false,
        latitude: 33.4152,
        longitude: -111.8315,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Kansas City',
        country: 'États-Unis',
        isDefault: false,
        latitude: 39.0997,
        longitude: -94.5786,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Atlanta',
        country: 'États-Unis',
        isDefault: false,
        latitude: 33.7490,
        longitude: -84.3880,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Long Beach',
        country: 'États-Unis',
        isDefault: false,
        latitude: 33.7701,
        longitude: -118.1937,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Colorado Springs',
        country: 'États-Unis',
        isDefault: false,
        latitude: 38.8339,
        longitude: -104.8214,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Raleigh',
        country: 'États-Unis',
        isDefault: false,
        latitude: 35.7796,
        longitude: -78.6382,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Miami',
        country: 'États-Unis',
        isDefault: false,
        latitude: 25.7617,
        longitude: -80.1918,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Virginia Beach',
        country: 'États-Unis',
        isDefault: false,
        latitude: 36.8529,
        longitude: -75.9780,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Omaha',
        country: 'États-Unis',
        isDefault: false,
        latitude: 41.2565,
        longitude: -95.9345,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Oakland',
        country: 'États-Unis',
        isDefault: false,
        latitude: 37.8044,
        longitude: -122.2712,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Minneapolis',
        country: 'États-Unis',
        isDefault: false,
        latitude: 44.9778,
        longitude: -93.2650,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Tulsa',
        country: 'États-Unis',
        isDefault: false,
        latitude: 36.1540,
        longitude: -95.9928,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'Arlington',
        country: 'États-Unis',
        isDefault: false,
        latitude: 32.7357,
        longitude: -97.1081,
        flag: '🇺🇸'),
    City(
        isSelected: false,
        city: 'New Orleans',
        country: 'États-Unis',
        isDefault: false,
        latitude: 29.9511,
        longitude: -90.0715,
        flag: '🇺🇸'),

    // CANADA
    City(
        isSelected: false,
        city: 'Toronto',
        country: 'Canada',
        isDefault: false,
        latitude: 43.6532,
        longitude: -79.3832,
        flag: '🇨🇦'),
    City(
        isSelected: false,
        city: 'Montreal',
        country: 'Canada',
        isDefault: false,
        latitude: 45.5017,
        longitude: -73.5673,
        flag: '🇨🇦'),
    City(
        isSelected: false,
        city: 'Vancouver',
        country: 'Canada',
        isDefault: false,
        latitude: 49.2827,
        longitude: -123.1207,
        flag: '🇨🇦'),
    City(
        isSelected: false,
        city: 'Calgary',
        country: 'Canada',
        isDefault: false,
        latitude: 51.0447,
        longitude: -114.0719,
        flag: '🇨🇦'),
    City(
        isSelected: false,
        city: 'Edmonton',
        country: 'Canada',
        isDefault: false,
        latitude: 53.5461,
        longitude: -113.4938,
        flag: '🇨🇦'),
    City(
        isSelected: false,
        city: 'Ottawa',
        country: 'Canada',
        isDefault: false,
        latitude: 45.4215,
        longitude: -75.6972,
        flag: '🇨🇦'),
    City(
        isSelected: false,
        city: 'Winnipeg',
        country: 'Canada',
        isDefault: false,
        latitude: 49.8951,
        longitude: -97.1384,
        flag: '🇨🇦'),
    City(
        isSelected: false,
        city: 'Quebec',
        country: 'Canada',
        isDefault: false,
        latitude: 46.8139,
        longitude: -71.2080,
        flag: '🇨🇦'),

    // JAPON
    City(
        isSelected: false,
        city: 'Tokyo',
        country: 'Japon',
        isDefault: false,
        latitude: 35.6762,
        longitude: 139.6503,
        flag: '🇯🇵'),
    City(
        isSelected: false,
        city: 'Osaka',
        country: 'Japon',
        isDefault: false,
        latitude: 34.6937,
        longitude: 135.5023,
        flag: '🇯🇵'),
    City(
        isSelected: false,
        city: 'Yokohama',
        country: 'Japon',
        isDefault: false,
        latitude: 35.4437,
        longitude: 139.6380,
        flag: '🇯🇵'),
    City(
        isSelected: false,
        city: 'Nagoya',
        country: 'Japon',
        isDefault: false,
        latitude: 35.1815,
        longitude: 136.9066,
        flag: '🇯🇵'),
    City(
        isSelected: false,
        city: 'Sapporo',
        country: 'Japon',
        isDefault: false,
        latitude: 43.0642,
        longitude: 141.3469,
        flag: '🇯🇵'),
    City(
        isSelected: false,
        city: 'Kobe',
        country: 'Japon',
        isDefault: false,
        latitude: 34.6901,
        longitude: 135.1956,
        flag: '🇯🇵'),
    City(
        isSelected: false,
        city: 'Kyoto',
        country: 'Japon',
        isDefault: false,
        latitude: 35.0116,
        longitude: 135.7681,
        flag: '🇯🇵'),
    City(
        isSelected: false,
        city: 'Fukuoka',
        country: 'Japon',
        isDefault: false,
        latitude: 33.5904,
        longitude: 130.4017,
        flag: '🇯🇵'),

    // CHINE
    City(
        isSelected: false,
        city: 'Pékin',
        country: 'Chine',
        isDefault: false,
        latitude: 39.9042,
        longitude: 116.4074,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Shanghai',
        country: 'Chine',
        isDefault: false,
        latitude: 31.2304,
        longitude: 121.4737,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Guangzhou',
        country: 'Chine',
        isDefault: false,
        latitude: 23.1291,
        longitude: 113.2644,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Shenzhen',
        country: 'Chine',
        isDefault: false,
        latitude: 22.5431,
        longitude: 114.0579,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Chengdu',
        country: 'Chine',
        isDefault: false,
        latitude: 30.5728,
        longitude: 104.0668,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Nanjing',
        country: 'Chine',
        isDefault: false,
        latitude: 32.0603,
        longitude: 118.7969,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Wuhan',
        country: 'Chine',
        isDefault: false,
        latitude: 30.5928,
        longitude: 114.3055,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Xi\'an',
        country: 'Chine',
        isDefault: false,
        latitude: 34.3416,
        longitude: 108.9398,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Hangzhou',
        country: 'Chine',
        isDefault: false,
        latitude: 30.2741,
        longitude: 120.1551,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Chongqing',
        country: 'Chine',
        isDefault: false,
        latitude: 29.4316,
        longitude: 106.9123,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Qingdao',
        country: 'Chine',
        isDefault: false,
        latitude: 36.0986,
        longitude: 120.3719,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Dalian',
        country: 'Chine',
        isDefault: false,
        latitude: 38.9140,
        longitude: 121.6147,
        flag: '🇨🇳'),
    City(
        isSelected: false,
        city: 'Hong Kong',
        country: 'Hong Kong',
        isDefault: false,
        latitude: 22.3193,
        longitude: 114.1694,
        flag: '🇭🇰'),

    // INDE
    City(
        isSelected: false,
        city: 'Mumbai',
        country: 'Inde',
        isDefault: false,
        latitude: 19.0760,
        longitude: 72.8777,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Delhi',
        country: 'Inde',
        isDefault: false,
        latitude: 28.7041,
        longitude: 77.1025,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Bangalore',
        country: 'Inde',
        isDefault: false,
        latitude: 12.9716,
        longitude: 77.5946,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Hyderabad',
        country: 'Inde',
        isDefault: false,
        latitude: 17.3850,
        longitude: 78.4867,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Ahmedabad',
        country: 'Inde',
        isDefault: false,
        latitude: 23.0225,
        longitude: 72.5714,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Chennai',
        country: 'Inde',
        isDefault: false,
        latitude: 13.0827,
        longitude: 80.2707,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Kolkata',
        country: 'Inde',
        isDefault: false,
        latitude: 22.5726,
        longitude: 88.3639,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Pune',
        country: 'Inde',
        isDefault: false,
        latitude: 18.5204,
        longitude: 73.8567,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Jaipur',
        country: 'Inde',
        isDefault: false,
        latitude: 26.9124,
        longitude: 75.7873,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Surat',
        country: 'Inde',
        isDefault: false,
        latitude: 21.1702,
        longitude: 72.8311,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Lucknow',
        country: 'Inde',
        isDefault: false,
        latitude: 26.8467,
        longitude: 80.9462,
        flag: '🇮🇳'),
    City(
        isSelected: false,
        city: 'Kanpur',
        country: 'Inde',
        isDefault: false,
        latitude: 26.4499,
        longitude: 80.3319,
        flag: '🇮🇳'),

    // AUSTRALIE
    City(
        isSelected: false,
        city: 'Sydney',
        country: 'Australie',
        isDefault: false,
        latitude: -33.8688,
        longitude: 151.2093,
        flag: '🇦🇺'),
    City(
        isSelected: false,
        city: 'Melbourne',
        country: 'Australie',
        isDefault: false,
        latitude: -37.8136,
        longitude: 144.9631,
        flag: '🇦🇺'),
    City(
        isSelected: false,
        city: 'Brisbane',
        country: 'Australie',
        isDefault: false,
        latitude: -27.4698,
        longitude: 153.0251,
        flag: '🇦🇺'),
    City(
        isSelected: false,
        city: 'Perth',
        country: 'Australie',
        isDefault: false,
        latitude: -31.9505,
        longitude: 115.8605,
        flag: '🇦🇺'),
    City(
        isSelected: false,
        city: 'Adelaide',
        country: 'Australie',
        isDefault: false,
        latitude: -34.9285,
        longitude: 138.6007,
        flag: '🇦🇺'),
    City(
        isSelected: false,
        city: 'Gold Coast',
        country: 'Australie',
        isDefault: false,
        latitude: -28.0167,
        longitude: 153.4000,
        flag: '🇦🇺'),
    City(
        isSelected: false,
        city: 'Newcastle',
        country: 'Australie',
        isDefault: false,
        latitude: -32.9283,
        longitude: 151.7817,
        flag: '🇦🇺'),
    City(
        isSelected: false,
        city: 'Canberra',
        country: 'Australie',
        isDefault: false,
        latitude: -35.2809,
        longitude: 149.1300,
        flag: '🇦🇺'),

    // BRÉSIL
    City(
        isSelected: false,
        city: 'São Paulo',
        country: 'Brésil',
        isDefault: false,
        latitude: -23.5505,
        longitude: -46.6333,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Rio de Janeiro',
        country: 'Brésil',
        isDefault: false,
        latitude: -22.9068,
        longitude: -43.1729,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Brasília',
        country: 'Brésil',
        isDefault: false,
        latitude: -15.8267,
        longitude: -47.9218,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Salvador',
        country: 'Brésil',
        isDefault: false,
        latitude: -12.9777,
        longitude: -38.5016,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Fortaleza',
        country: 'Brésil',
        isDefault: false,
        latitude: -3.7319,
        longitude: -38.5267,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Belo Horizonte',
        country: 'Brésil',
        isDefault: false,
        latitude: -19.8157,
        longitude: -43.9542,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Manaus',
        country: 'Brésil',
        isDefault: false,
        latitude: -3.1190,
        longitude: -60.0217,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Curitiba',
        country: 'Brésil',
        isDefault: false,
        latitude: -25.4244,
        longitude: -49.2654,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Recife',
        country: 'Brésil',
        isDefault: false,
        latitude: -8.0476,
        longitude: -34.8770,
        flag: '🇧🇷'),
    City(
        isSelected: false,
        city: 'Porto Alegre',
        country: 'Brésil',
        isDefault: false,
        latitude: -30.0346,
        longitude: -51.2177,
        flag: '🇧🇷'),

    // AFRIQUE
    City(
        isSelected: false,
        city: 'Lagos',
        country: 'Nigeria',
        isDefault: false,
        latitude: 6.5244,
        longitude: 3.3792,
        flag: '🇳🇬'),
    City(
        isSelected: false,
        city: 'Kinshasa',
        country: 'RD Congo',
        isDefault: false,
        latitude: -4.4419,
        longitude: 15.2663,
        flag: '🇨🇩'),
    City(
        isSelected: false,
        city: 'Luanda',
        country: 'Angola',
        isDefault: false,
        latitude: -8.8390,
        longitude: 13.2894,
        flag: '🇦🇴'),
    City(
        isSelected: false,
        city: 'Dar es Salaam',
        country: 'Tanzanie',
        isDefault: false,
        latitude: -6.7924,
        longitude: 39.2083,
        flag: '🇹🇿'),
    City(
        isSelected: false,
        city: 'Khartoum',
        country: 'Soudan',
        isDefault: false,
        latitude: 15.5007,
        longitude: 32.5599,
        flag: '🇸🇩'),
    City(
        isSelected: false,
        city: 'Alexandrie',
        country: 'Égypte',
        isDefault: false,
        latitude: 31.2001,
        longitude: 29.9187,
        flag: '🇪🇬'),
    City(
        isSelected: false,
        city: 'Abidjan',
        country: 'Côte d\'Ivoire',
        isDefault: false,
        latitude: 5.3600,
        longitude: -4.0083,
        flag: '🇨🇮'),
    City(
        isSelected: false,
        city: 'Kano',
        country: 'Nigeria',
        isDefault: false,
        latitude: 12.0022,
        longitude: 8.5920,
        flag: '🇳🇬'),
    City(
        isSelected: false,
        city: 'Ibadan',
        country: 'Nigeria',
        isDefault: false,
        latitude: 7.3775,
        longitude: 3.9470,
        flag: '🇳🇬'),
    City(
        isSelected: false,
        city: 'Le Cap',
        country: 'Afrique du Sud',
        isDefault: false,
        latitude: -33.9249,
        longitude: 18.4241,
        flag: '🇿🇦'),
    City(
        isSelected: false,
        city: 'Johannesburg',
        country: 'Afrique du Sud',
        isDefault: false,
        latitude: -26.2041,
        longitude: 28.0473,
        flag: '🇿🇦'),
    City(
        isSelected: false,
        city: 'Durban',
        country: 'Afrique du Sud',
        isDefault: false,
        latitude: -29.8587,
        longitude: 31.0218,
        flag: '🇿🇦'),
    City(
        isSelected: false,
        city: 'Accra',
        country: 'Ghana',
        isDefault: false,
        latitude: 5.6037,
        longitude: -0.1870,
        flag: '🇬🇭'),
    City(
        isSelected: false,
        city: 'Dakar',
        country: 'Sénégal',
        isDefault: false,
        latitude: 14.6928,
        longitude: -17.4467,
        flag: '🇸🇳'),
    City(
        isSelected: false,
        city: 'Bamako',
        country: 'Mali',
        isDefault: false,
        latitude: 12.6500,
        longitude: -8.0000,
        flag: '🇲🇱'),
    City(
        isSelected: false,
        city: 'Ouagadougou',
        country: 'Burkina Faso',
        isDefault: false,
        latitude: 12.3714,
        longitude: -1.5197,
        flag: '🇧🇫'),
    City(
        isSelected: false,
        city: 'Niamey',
        country: 'Niger',
        isDefault: false,
        latitude: 13.5116,
        longitude: 2.1254,
        flag: '🇳🇪'),
    City(
        isSelected: false,
        city: 'Conakry',
        country: 'Guinée',
        isDefault: false,
        latitude: 9.6412,
        longitude: -13.5784,
        flag: '🇬🇳'),
    City(
        isSelected: false,
        city: 'Freetown',
        country: 'Sierra Leone',
        isDefault: false,
        latitude: 8.4657,
        longitude: -13.2317,
        flag: '🇸🇱'),
    City(
        isSelected: false,
        city: 'Monrovia',
        country: 'Liberia',
        isDefault: false,
        latitude: 6.2907,
        longitude: -10.7605,
        flag: '🇱🇷'),
    City(
        isSelected: false,
        city: 'Cotonou',
        country: 'Bénin',
        isDefault: false,
        latitude: 6.4031,
        longitude: 2.5085,
        flag: '🇧🇯'),
    City(
        isSelected: false,
        city: 'Porto-Novo',
        country: 'Bénin',
        isDefault: false,
        latitude: 6.4969,
        longitude: 2.6283,
        flag: '🇧🇯'),
    City(
        isSelected: false,
        city: 'Libreville',
        country: 'Gabon',
        isDefault: false,
        latitude: 0.4162,
        longitude: 9.4673,
        flag: '🇬🇦'),
    City(
        isSelected: false,
        city: 'Malabo',
        country: 'Guinée équatoriale',
        isDefault: false,
        latitude: 3.7558,
        longitude: 8.7819,
        flag: '🇬🇶'),
    City(
        isSelected: false,
        city: 'Praia',
        country: 'Cap-Vert',
        isDefault: false,
        latitude: 14.9177,
        longitude: -23.5092,
        flag: '🇨🇻'),
    City(
        isSelected: false,
        city: 'Bissau',
        country: 'Guinée-Bissau',
        isDefault: false,
        latitude: 11.8817,
        longitude: -15.6178,
        flag: '🇬🇼'),
    City(
        isSelected: false,
        city: 'Tunis',
        country: 'Tunisie',
        isDefault: false,
        latitude: 36.8065,
        longitude: 10.1815,
        flag: '🇹🇳'),
    City(
        isSelected: false,
        city: 'Alger',
        country: 'Algérie',
        isDefault: false,
        latitude: 36.7538,
        longitude: 3.0588,
        flag: '🇩🇿'),
    City(
        isSelected: false,
        city: 'Rabat',
        country: 'Maroc',
        isDefault: false,
        latitude: 34.0209,
        longitude: -6.8416,
        flag: '🇲🇦'),
    City(
        isSelected: false,
        city: 'Casablanca',
        country: 'Maroc',
        isDefault: false,
        latitude: 33.5731,
        longitude: -7.5898,
        flag: '🇲🇦'),
    City(
        isSelected: false,
        city: 'Le Caire',
        country: 'Égypte',
        isDefault: false,
        latitude: 30.0444,
        longitude: 31.2357,
        flag: '🇪🇬'),
    City(
        isSelected: false,
        city: 'Nairobi',
        country: 'Kenya',
        isDefault: false,
        latitude: -1.2921,
        longitude: 36.8219,
        flag: '🇰🇪'),
    City(
        isSelected: false,
        city: 'Addis-Abeba',
        country: 'Éthiopie',
        isDefault: false,
        latitude: 9.1450,
        longitude: 40.4897,
        flag: '🇪🇹'),
    City(
        isSelected: false,
        city: 'Kampala',
        country: 'Ouganda',
        isDefault: false,
        latitude: 0.3476,
        longitude: 32.5825,
        flag: '🇺🇬'),
    City(
        isSelected: false,
        city: 'Kigali',
        country: 'Rwanda',
        isDefault: false,
        latitude: -1.9706,
        longitude: 30.1044,
        flag: '🇷🇼'),
    City(
        isSelected: false,
        city: 'Bujumbura',
        country: 'Burundi',
        isDefault: false,
        latitude: -3.3614,
        longitude: 29.3599,
        flag: '🇧🇮'),
    City(
        isSelected: false,
        city: 'Djibouti',
        country: 'Djibouti',
        isDefault: false,
        latitude: 11.8251,
        longitude: 42.5903,
        flag: '🇩🇯'),
    City(
        isSelected: false,
        city: 'Asmara',
        country: 'Érythrée',
        isDefault: false,
        latitude: 15.3229,
        longitude: 38.9251,
        flag: '🇪🇷'),
    City(
        isSelected: false,
        city: 'Mogadiscio',
        country: 'Somalie',
        isDefault: false,
        latitude: 2.0469,
        longitude: 45.3182,
        flag: '🇸🇴'),
    City(
        isSelected: false,
        city: 'Mango',
        country: 'Togo',
        isDefault: false,
        region: 'Savanes',
        latitude: 10.3667,
        longitude: 0.4667),
    City(
        isSelected: false,
        city: 'Tabligbo',
        country: 'Togo',
        isDefault: false,
        region: 'Maritime',
        latitude: 6.5667,
        longitude: 1.5000),
    City(
        isSelected: false,
        city: 'Notse',
        country: 'Togo',
        isDefault: false,
        region: 'Plateaux',
        latitude: 6.9500,
        longitude: 1.1667),
    City(
        isSelected: false,
        city: 'Vogan',
        country: 'Togo',
        isDefault: false,
        region: 'Maritime',
        latitude: 6.3167,
        longitude: 1.5333),
    City(
        isSelected: false,
        city: 'Bafilo',
        country: 'Togo',
        isDefault: false,
        region: 'Kara',
        latitude: 9.3500,
        longitude: 1.2667),
    City(
        isSelected: false,
        city: 'Badou',
        country: 'Togo',
        isDefault: false,
        region: 'Plateaux',
        latitude: 7.5833,
        longitude: 0.6000),
    City(
        isSelected: false,
        city: 'Kandé',
        country: 'Togo',
        isDefault: false,
        region: 'Kara',
        latitude: 9.9500,
        longitude: 1.0333),
    City(
        isSelected: false,
        city: 'Niamtougou',
        country: 'Togo',
        isDefault: false,
        region: 'Kara',
        latitude: 9.7667,
        longitude: 1.1000),
    City(
        isSelected: false,
        city: 'Kéméni',
        country: 'Togo',
        isDefault: false,
        region: 'Centrale',
        latitude: 8.9167,
        longitude: 0.8167),
    City(
        isSelected: false,
        city: 'Tchamba',
        country: 'Togo',
        isDefault: false,
        region: 'Centrale',
        latitude: 9.0333,
        longitude: 1.4167),
    City(
        isSelected: false,
        city: 'Sansanné-Mango',
        country: 'Togo',
        isDefault: false,
        region: 'Savanes',
        latitude: 10.3500,
        longitude: 0.4500),

    // AFRIQUE DE L'OUEST
    City(
        isSelected: false,
        city: 'Accra',
        country: 'Ghana',
        isDefault: false,
        region: 'Greater Accra',
        latitude: 5.6037,
        longitude: -0.1870),
    City(
        isSelected: false,
        city: 'Kumasi',
        country: 'Ghana',
        isDefault: false,
        region: 'Ashanti',
        latitude: 6.6885,
        longitude: -1.6244),
    City(
        isSelected: false,
        city: 'Abidjan',
        country: 'Côte d\'Ivoire',
        isDefault: false,
        region: 'Lagunes',
        latitude: 5.3599,
        longitude: -4.0083),
    City(
        isSelected: false,
        city: 'Yamoussoukro',
        country: 'Côte d\'Ivoire',
        isDefault: false,
        region: 'Lacs',
        latitude: 6.8276,
        longitude: -5.2893),
    City(
        isSelected: false,
        city: 'Ouagadougou',
        country: 'Burkina Faso',
        isDefault: false,
        region: 'Centre',
        latitude: 12.3714,
        longitude: -1.5197),
    City(
        isSelected: false,
        city: 'Bobo-Dioulasso',
        country: 'Burkina Faso',
        isDefault: false,
        region: 'Hauts-Bassins',
        latitude: 11.1785,
        longitude: -4.2979),
    City(
        isSelected: false,
        city: 'Bamako',
        country: 'Mali',
        isDefault: false,
        region: 'Bamako',
        latitude: 12.6392,
        longitude: -8.0029),
    City(
        isSelected: false,
        city: 'Lagos',
        country: 'Nigeria',
        isDefault: false,
        region: 'Lagos',
        latitude: 6.5244,
        longitude: 3.3792),
    City(
        isSelected: false,
        city: 'Abuja',
        country: 'Nigeria',
        isDefault: false,
        region: 'FCT',
        latitude: 9.0765,
        longitude: 7.3986),
    City(
        isSelected: false,
        city: 'Kano',
        country: 'Nigeria',
        isDefault: false,
        region: 'Kano',
        latitude: 12.0022,
        longitude: 8.5920),
    City(
        isSelected: false,
        city: 'Ibadan',
        country: 'Nigeria',
        isDefault: false,
        region: 'Oyo',
        latitude: 7.3775,
        longitude: 3.9470),
    City(
        isSelected: false,
        city: 'Dakar',
        country: 'Sénégal',
        isDefault: false,
        region: 'Dakar',
        latitude: 14.7167,
        longitude: -17.4677),
    City(
        isSelected: false,
        city: 'Cotonou',
        country: 'Bénin',
        isDefault: false,
        region: 'Littoral',
        latitude: 6.4023,
        longitude: 2.5059),
    City(
        isSelected: false,
        city: 'Porto-Novo',
        country: 'Bénin',
        isDefault: false,
        region: 'Ouémé',
        latitude: 6.4968,
        longitude: 2.6281),
    City(
        isSelected: false,
        city: 'Niamey',
        country: 'Niger',
        isDefault: false,
        region: 'Niamey',
        latitude: 13.5116,
        longitude: 2.1254),
    City(
        isSelected: false,
        city: 'Conakry',
        country: 'Guinée',
        isDefault: false,
        region: 'Conakry',
        latitude: 9.6412,
        longitude: -13.5784),
    City(
        isSelected: false,
        city: 'Bissau',
        country: 'Guinée-Bissau',
        isDefault: false,
        region: 'Bissau',
        latitude: 11.8816,
        longitude: -15.6178),
    City(
        isSelected: false,
        city: 'Freetown',
        country: 'Sierra Leone',
        isDefault: false,
        region: 'Western Area',
        latitude: 8.4840,
        longitude: -13.2299),
    City(
        isSelected: false,
        city: 'Monrovia',
        country: 'Liberia',
        isDefault: false,
        region: 'Montserrado',
        latitude: 6.2907,
        longitude: -10.7605),

    // AFRIQUE CENTRALE
    City(
        isSelected: false,
        city: 'Yaoundé',
        country: 'Cameroun',
        isDefault: false,
        region: 'Centre',
        latitude: 3.8480,
        longitude: 11.5021),
    City(
        isSelected: false,
        city: 'Douala',
        country: 'Cameroun',
        isDefault: false,
        region: 'Littoral',
        latitude: 4.0511,
        longitude: 9.7679),
    City(
        isSelected: false,
        city: 'Libreville',
        country: 'Gabon',
        isDefault: false,
        region: 'Estuaire',
        latitude: 0.4162,
        longitude: 9.4673),
    City(
        isSelected: false,
        city: 'Brazzaville',
        country: 'Congo',
        isDefault: false,
        region: 'Brazzaville',
        latitude: -4.2634,
        longitude: 15.2429),
    City(
        isSelected: false,
        city: 'Kinshasa',
        country: 'RD Congo',
        isDefault: false,
        region: 'Kinshasa',
        latitude: -4.4419,
        longitude: 15.2663),
    City(
        isSelected: false,
        city: 'Bangui',
        country: 'Centrafrique',
        isDefault: false,
        region: 'Bangui',
        latitude: 4.3947,
        longitude: 18.5582),
    City(
        isSelected: false,
        city: 'N\'Djamena',
        country: 'Tchad',
        isDefault: false,
        region: 'N\'Djamena',
        latitude: 12.1348,
        longitude: 15.0557),

    // AFRIQUE DE L'EST
    City(
        isSelected: false,
        city: 'Nairobi',
        country: 'Kenya',
        isDefault: false,
        region: 'Nairobi',
        latitude: -1.2921,
        longitude: 36.8219),
    City(
        isSelected: false,
        city: 'Kampala',
        country: 'Ouganda',
        isDefault: false,
        region: 'Central',
        latitude: 0.3476,
        longitude: 32.5825),
    City(
        isSelected: false,
        city: 'Dar es Salaam',
        country: 'Tanzanie',
        isDefault: false,
        region: 'Dar es Salaam',
        latitude: -6.7924,
        longitude: 39.2083),
    City(
        isSelected: false,
        city: 'Addis-Abeba',
        country: 'Éthiopie',
        isDefault: false,
        region: 'Addis-Abeba',
        latitude: 9.1450,
        longitude: 40.4897),
    City(
        isSelected: false,
        city: 'Kigali',
        country: 'Rwanda',
        isDefault: false,
        region: 'Kigali',
        latitude: -1.9706,
        longitude: 30.1044),
    City(
        isSelected: false,
        city: 'Bujumbura',
        country: 'Burundi',
        isDefault: false,
        region: 'Bujumbura Mairie',
        latitude: -3.3761,
        longitude: 29.3628),
    City(
        isSelected: false,
        city: 'Djibouti',
        country: 'Djibouti',
        isDefault: false,
        region: 'Djibouti',
        latitude: 11.8251,
        longitude: 42.5903),
    City(
        isSelected: false,
        city: 'Mogadiscio',
        country: 'Somalie',
        isDefault: false,
        region: 'Banaadir',
        latitude: 2.0469,
        longitude: 45.3182),

    // AFRIQUE AUSTRALE
    City(
        isSelected: false,
        city: 'Le Cap',
        country: 'Afrique du Sud',
        isDefault: false,
        region: 'Western Cape',
        latitude: -33.9249,
        longitude: 18.4241),
    City(
        isSelected: false,
        city: 'Johannesburg',
        country: 'Afrique du Sud',
        isDefault: false,
        region: 'Gauteng',
        latitude: -26.2041,
        longitude: 28.0473),
    City(
        isSelected: false,
        city: 'Pretoria',
        country: 'Afrique du Sud',
        isDefault: false,
        region: 'Gauteng',
        latitude: -25.7479,
        longitude: 28.2293),
    City(
        isSelected: false,
        city: 'Durban',
        country: 'Afrique du Sud',
        isDefault: false,
        region: 'KwaZulu-Natal',
        latitude: -29.8587,
        longitude: 31.0218),
    City(
        isSelected: false,
        city: 'Windhoek',
        country: 'Namibie',
        isDefault: false,
        region: 'Khomas',
        latitude: -22.5609,
        longitude: 17.0658),
    City(
        isSelected: false,
        city: 'Gaborone',
        country: 'Botswana',
        isDefault: false,
        region: 'South-East',
        latitude: -24.6282,
        longitude: 25.9231),
    City(
        isSelected: false,
        city: 'Lusaka',
        country: 'Zambie',
        isDefault: false,
        region: 'Lusaka',
        latitude: -15.3875,
        longitude: 28.3228),
    City(
        isSelected: false,
        city: 'Harare',
        country: 'Zimbabwe',
        isDefault: false,
        region: 'Harare',
        latitude: -17.8292,
        longitude: 31.0522),

    // AFRIQUE DU NORD
    City(
        isSelected: false,
        city: 'Le Caire',
        country: 'Égypte',
        isDefault: false,
        region: 'Le Caire',
        latitude: 30.0444,
        longitude: 31.2357),
    City(
        isSelected: false,
        city: 'Alexandrie',
        country: 'Égypte',
        isDefault: false,
        region: 'Alexandrie',
        latitude: 31.2001,
        longitude: 29.9187),
    City(
        isSelected: false,
        city: 'Tripoli',
        country: 'Libye',
        isDefault: false,
        region: 'Tripoli',
        latitude: 32.8872,
        longitude: 13.1913),
    City(
        isSelected: false,
        city: 'Tunis',
        country: 'Tunisie',
        isDefault: false,
        region: 'Tunis',
        latitude: 36.8065,
        longitude: 10.1815),
    City(
        isSelected: false,
        city: 'Alger',
        country: 'Algérie',
        isDefault: false,
        region: 'Alger',
        latitude: 36.7372,
        longitude: 3.0865),
    City(
        isSelected: false,
        city: 'Casablanca',
        country: 'Maroc',
        isDefault: false,
        region: 'Casablanca-Settat',
        latitude: 33.5731,
        longitude: -7.5898),
    City(
        isSelected: false,
        city: 'Rabat',
        country: 'Maroc',
        isDefault: false,
        region: 'Rabat-Salé-Kénitra',
        latitude: 34.0209,
        longitude: -6.8416),

    // Quelques villes internationales majeures
    City(
        isSelected: false,
        city: 'Londres',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 51.5074,
        longitude: -0.1278),
    City(
        isSelected: false,
        city: 'Paris',
        country: 'France',
        isDefault: false,
        latitude: 48.8566,
        longitude: 2.3522),
    City(
        isSelected: false,
        city: 'New York',
        country: 'États-Unis',
        isDefault: false,
        latitude: 40.7128,
        longitude: -74.0060),
    City(
        isSelected: false,
        city: 'Tokyo',
        country: 'Japon',
        isDefault: false,
        latitude: 35.6762,
        longitude: 139.6503),
    City(
        isSelected: false,
        city: 'São Paulo',
        country: 'Brazil',
        isDefault: false),
    City(isSelected: false, city: 'Cairo', country: 'Egypt', isDefault: false),
    City(
        isSelected: false,
        city: 'Bangkok',
        country: 'Thailand',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Buenos Aires',
        country: 'Argentina',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Istanbul',
        country: 'Turkey',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Seoul',
        country: 'South Korea',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Mexico City',
        country: 'Mexico',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Jakarta',
        country: 'Indonesia',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Algiers',
        country: 'Algeria',
        isDefault: false),
    City(
        isSelected: false, city: 'Luanda', country: 'Angola', isDefault: false),
    City(
        isSelected: false,
        city: 'Porto-Novo',
        country: 'Benin',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Gaborone',
        country: 'Botswana',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Ouagadougou',
        country: 'Burkina Faso',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Bujumbura',
        country: 'Burundi',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Yaoundé',
        country: 'Cameroon',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Praia',
        country: 'Cape Verde',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Bangui',
        country: 'Central African Republic',
        isDefault: false),
    City(
        isSelected: false,
        city: 'N Djamena',
        country: 'Chad',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Moroni',
        country: 'Comoros',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Brazzaville',
        country: 'Congo',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Yamoussoukro',
        country: 'Ivory Coast',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Djibouti',
        country: 'Djibouti',
        isDefault: false),
    City(isSelected: false, city: 'Cairo', country: 'Egypt', isDefault: false),
    City(
        isSelected: false,
        city: 'Malabo',
        country: 'Equatorial Guinea',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Asmara',
        country: 'Eritrea',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Addis Ababa',
        country: 'Ethiopia',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Libreville',
        country: 'Gabon',
        isDefault: false),
    City(
        isSelected: false, city: 'Banjul', country: 'Gambia', isDefault: false),
    City(isSelected: false, city: 'Accra', country: 'Ghana', isDefault: false),
    City(
        isSelected: false,
        city: 'Conakry',
        country: 'Guinea',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Bissau',
        country: 'Guinea-Bissau',
        isDefault: false),
    City(
        isSelected: false, city: 'Nairobi', country: 'Kenya', isDefault: false),
    City(
        isSelected: false,
        city: 'Maseru',
        country: 'Lesotho',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Monrovia',
        country: 'Liberia',
        isDefault: false),
    City(
        isSelected: false, city: 'Tripoli', country: 'Libya', isDefault: false),
    City(
        isSelected: false,
        city: 'Antananarivo',
        country: 'Madagascar',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Lilongwe',
        country: 'Malawi',
        isDefault: false),
    City(isSelected: false, city: 'Bamako', country: 'Mali', isDefault: false),
    City(
        isSelected: false,
        city: 'Nouakchott',
        country: 'Mauritania',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Port Louis',
        country: 'Mauritius',
        isDefault: false),
    City(
        isSelected: false, city: 'Rabat', country: 'Morocco', isDefault: false),
    City(
        isSelected: false,
        city: 'Maputo',
        country: 'Mozambique',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Windhoek',
        country: 'Namibia',
        isDefault: false),
    City(isSelected: false, city: 'Niamey', country: 'Niger', isDefault: false),
    City(
        isSelected: false, city: 'Abuja', country: 'Nigeria', isDefault: false),
    City(
        isSelected: false, city: 'Kigali', country: 'Rwanda', isDefault: false),
    City(
        isSelected: false,
        city: 'São Tomé',
        country: 'São Tomé and Príncipe',
        isDefault: false),
    City(
        isSelected: false, city: 'Dakar', country: 'Senegal', isDefault: false),
    City(
        isSelected: false,
        city: 'Victoria',
        country: 'Seychelles',
        isDefault: false),
    City(
        isSelected: false,
        city: 'Freetown',
        country: 'Sierra Leone',
        isDefault: false),

    // CAPITALES MONDIALES
    City(
        isSelected: false,
        city: 'Paris',
        country: 'France',
        isDefault: false,
        latitude: 48.8566,
        longitude: 2.3522),
    City(
        isSelected: false,
        city: 'Londres',
        country: 'Royaume-Uni',
        isDefault: false,
        latitude: 51.5074,
        longitude: -0.1278),
    City(
        isSelected: false,
        city: 'New York',
        country: 'États-Unis',
        isDefault: false,
        latitude: 40.7128,
        longitude: -74.0060),
    City(
        isSelected: false,
        city: 'Tokyo',
        country: 'Japon',
        isDefault: false,
        latitude: 35.6762,
        longitude: 139.6503),
    City(
        isSelected: false,
        city: 'Berlin',
        country: 'Allemagne',
        isDefault: false,
        latitude: 52.5200,
        longitude: 13.4050),
    City(
        isSelected: false,
        city: 'Madrid',
        country: 'Espagne',
        isDefault: false,
        latitude: 40.4168,
        longitude: -3.7038),
    City(
        isSelected: false,
        city: 'Rome',
        country: 'Italie',
        isDefault: false,
        latitude: 41.9028,
        longitude: 12.4964),
    City(
        isSelected: false,
        city: 'Moscou',
        country: 'Russie',
        isDefault: false,
        latitude: 55.7558,
        longitude: 37.6176),
    City(
        isSelected: false,
        city: 'Pékin',
        country: 'Chine',
        isDefault: false,
        latitude: 39.9042,
        longitude: 116.4074),
    City(
        isSelected: false,
        city: 'Mumbai',
        country: 'Inde',
        isDefault: false,
        latitude: 19.0760,
        longitude: 72.8777),
    City(
        isSelected: false,
        city: 'Dubaï',
        country: 'Émirats Arabes Unis',
        isDefault: false,
        latitude: 25.2048,
        longitude: 55.2708),
    City(
        isSelected: false,
        city: 'Sydney',
        country: 'Australie',
        isDefault: false,
        latitude: -33.8688,
        longitude: 151.2093),
    City(
        isSelected: false,
        city: 'Toronto',
        country: 'Canada',
        isDefault: false,
        latitude: 43.6532,
        longitude: -79.3832),
    City(
        isSelected: false,
        city: 'São Paulo',
        country: 'Brésil',
        isDefault: false,
        latitude: -23.5505,
        longitude: -46.6333),
    City(
        isSelected: false,
        city: 'Mexico',
        country: 'Mexique',
        isDefault: false,
        latitude: 19.4326,
        longitude: -99.1332),
    City(
        isSelected: false,
        city: 'Buenos Aires',
        country: 'Argentine',
        isDefault: false,
        latitude: -34.6118,
        longitude: -58.3960),
    City(
        isSelected: false,
        city: 'Amsterdam',
        country: 'Pays-Bas',
        isDefault: false,
        latitude: 52.3676,
        longitude: 4.9041),
    City(
        isSelected: false,
        city: 'Barcelone',
        country: 'Espagne',
        isDefault: false,
        latitude: 41.3851,
        longitude: 2.1734),
    City(
        isSelected: false,
        city: 'Lisbonne',
        country: 'Portugal',
        isDefault: false,
        latitude: 38.7223,
        longitude: -9.1393),
    City(
        isSelected: false,
        city: 'Vienne',
        country: 'Autriche',
        isDefault: false,
        latitude: 48.2082,
        longitude: 16.3738),
    City(
        isSelected: false,
        city: 'Prague',
        country: 'République Tchèque',
        isDefault: false,
        latitude: 50.0755,
        longitude: 14.4378),
    City(
        isSelected: false,
        city: 'Budapest',
        country: 'Hongrie',
        isDefault: false,
        latitude: 47.4979,
        longitude: 19.0402),
    City(
        isSelected: false,
        city: 'Varsovie',
        country: 'Pologne',
        isDefault: false,
        latitude: 52.2297,
        longitude: 21.0122),
    City(
        isSelected: false,
        city: 'Stockholm',
        country: 'Suède',
        isDefault: false,
        latitude: 59.3293,
        longitude: 18.0686),
    City(
        isSelected: false,
        city: 'Los Angeles',
        country: 'États-Unis',
        isDefault: false,
        latitude: 34.0522,
        longitude: -118.2437),
    City(
        isSelected: false,
        city: 'Chicago',
        country: 'États-Unis',
        isDefault: false,
        latitude: 41.8781,
        longitude: -87.6298),
    City(
        isSelected: false,
        city: 'Miami',
        country: 'États-Unis',
        isDefault: false,
        latitude: 25.7617,
        longitude: -80.1918),
    City(
        isSelected: false,
        city: 'Singapour',
        country: 'Singapour',
        isDefault: false,
        latitude: 1.3521,
        longitude: 103.8198),
    City(
        isSelected: false,
        city: 'Hong Kong',
        country: 'Chine',
        isDefault: false,
        latitude: 22.3193,
        longitude: 114.1694),
    City(
        isSelected: false,
        city: 'Shanghai',
        country: 'Chine',
        isDefault: false,
        latitude: 31.2304,
        longitude: 121.4737),
    City(
        isSelected: false,
        city: 'Bangkok',
        country: 'Thaïlande',
        isDefault: false,
        latitude: 13.7563,
        longitude: 100.5018),
    City(
        isSelected: false,
        city: 'Kuala Lumpur',
        country: 'Malaisie',
        isDefault: false,
        latitude: 3.1390,
        longitude: 101.6869),
    City(
        isSelected: false,
        city: 'Jakarta',
        country: 'Indonésie',
        isDefault: false,
        latitude: -6.2088,
        longitude: 106.8456),
    City(
        isSelected: false,
        city: 'Séoul',
        country: 'Corée du Sud',
        isDefault: false,
        latitude: 37.5665,
        longitude: 126.9780),
    City(
        isSelected: false,
        city: 'Melbourne',
        country: 'Australie',
        isDefault: false,
        latitude: -37.8136,
        longitude: 144.9631),
    City(
        isSelected: false,
        city: 'Auckland',
        country: 'Nouvelle-Zélande',
        isDefault: false,
        latitude: -36.8485,
        longitude: 174.7633),
  ];

  // Méthode pour obtenir les villes sélectionnées
  static List<City> getSelectedCities() {
    List<City> selectedCities = City.citiesList;
    return selectedCities.where((city) => city.isSelected == true).toList();
  }

  // Méthode pour rechercher des villes
  static List<City> searchCities(String query) {
    if (query.isEmpty) return citiesList;

    return citiesList.where((city) {
      return city.city.toLowerCase().contains(query.toLowerCase()) ||
          city.country.toLowerCase().contains(query.toLowerCase()) ||
          (city.region?.toLowerCase().contains(query.toLowerCase()) ?? false);
    }).toList();
  }
}
